// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Serilog.DataAccess.Context;

#nullable disable

namespace Serilog.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240123203841_mig_2")]
    partial class mig_2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Serilog.Core.Entities.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Serilog.Core.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Serilog.Core.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Geyim",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Image = "http://lorempixel.com/640/480/nightlife",
                            Name = "Parlaq Rezin Sviter"
                        },
                        new
                        {
                            Id = 2,
                            Category = "İdman",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Image = "http://lorempixel.com/640/480/people",
                            Name = "Əlverişli Qranit Sviter"
                        },
                        new
                        {
                            Id = 3,
                            Category = "bəzək",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Image = "http://lorempixel.com/640/480/transport",
                            Name = "İnanılmaz Pambıq Kulon"
                        },
                        new
                        {
                            Id = 4,
                            Category = "bəzək",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Image = "http://lorempixel.com/640/480/animals",
                            Name = "Əlverişli Qranit Beret"
                        },
                        new
                        {
                            Id = 5,
                            Category = "turizm",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Image = "http://lorempixel.com/640/480/nightlife",
                            Name = "İntellektual Ağac Stol"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Ayyaqqabı",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Image = "http://lorempixel.com/640/480/cats",
                            Name = "Fantastik Beton Kulon"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Kitablar",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Image = "http://lorempixel.com/640/480/transport",
                            Name = "Ergonomik Rezin Avtomobil"
                        },
                        new
                        {
                            Id = 8,
                            Category = "uşaq üçün",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Image = "http://lorempixel.com/640/480/sports",
                            Name = "Kobud Beton Avtomobil"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Səhiyyə",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Image = "http://lorempixel.com/640/480/city",
                            Name = "Kobud Qranit Kompyuter"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Filmlər",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Image = "http://lorempixel.com/640/480/cats",
                            Name = "Əlverişli Qranit Kəmər"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Geyim",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Image = "http://lorempixel.com/640/480/cats",
                            Name = "İntellektual Beton Kulon"
                        },
                        new
                        {
                            Id = 12,
                            Category = "bəzək",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Image = "http://lorempixel.com/640/480/cats",
                            Name = "Möhtəşəm Polad Kulon"
                        },
                        new
                        {
                            Id = 13,
                            Category = "садинструмент",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Image = "http://lorempixel.com/640/480/fashion",
                            Name = "İnanılmaz Ağac Kəmər"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Kompyuterlər",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Image = "http://lorempixel.com/640/480/fashion",
                            Name = "Kobud Plastik Beret"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Oyuncaqlar",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Image = "http://lorempixel.com/640/480/sports",
                            Name = "Fantastik Beton Sviter"
                        },
                        new
                        {
                            Id = 16,
                            Category = "gözəllik",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Image = "http://lorempixel.com/640/480/animals",
                            Name = "Balaca Pambıq Kulon"
                        },
                        new
                        {
                            Id = 17,
                            Category = "gözəllik",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Image = "http://lorempixel.com/640/480/fashion",
                            Name = "Kobud Qranit Avtomobil"
                        },
                        new
                        {
                            Id = 18,
                            Category = "musiqi",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Image = "http://lorempixel.com/640/480/business",
                            Name = "Parlaq Plastik Stol"
                        },
                        new
                        {
                            Id = 19,
                            Category = "uşaq üçün",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Image = "http://lorempixel.com/640/480/city",
                            Name = "İnanılmaz Qranit Stol"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Ayyaqqabı",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Image = "http://lorempixel.com/640/480/business",
                            Name = "İnanılmaz Ağac Sviter"
                        },
                        new
                        {
                            Id = 21,
                            Category = "садинструмент",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Image = "http://lorempixel.com/640/480/food",
                            Name = "Parlaq Qranit Kəmər"
                        },
                        new
                        {
                            Id = 22,
                            Category = "musiqi",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Image = "http://lorempixel.com/640/480/nature",
                            Name = "İntellektual Beton Avtomobil"
                        },
                        new
                        {
                            Id = 23,
                            Category = "садинструмент",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Image = "http://lorempixel.com/640/480/technics",
                            Name = "Əlverişli Rezin Avtomobil"
                        },
                        new
                        {
                            Id = 24,
                            Category = "bəzək",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Image = "http://lorempixel.com/640/480/nature",
                            Name = "İntellektual Pambıq Stol"
                        },
                        new
                        {
                            Id = 25,
                            Category = "Geyim",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Image = "http://lorempixel.com/640/480/abstract",
                            Name = "İnanılmaz Plastik Sviter"
                        },
                        new
                        {
                            Id = 26,
                            Category = "садинструмент",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Image = "http://lorempixel.com/640/480/business",
                            Name = "Ergonomik Beton Kulon"
                        },
                        new
                        {
                            Id = 27,
                            Category = "bəzək",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Image = "http://lorempixel.com/640/480/people",
                            Name = "İntellektual Ağac Kəmər"
                        },
                        new
                        {
                            Id = 28,
                            Category = "İdman",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Image = "http://lorempixel.com/640/480/transport",
                            Name = "Möhtəşəm Beton Stul"
                        },
                        new
                        {
                            Id = 29,
                            Category = "İdman",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Image = "http://lorempixel.com/640/480/nature",
                            Name = "Parlaq Ağac Sviter"
                        },
                        new
                        {
                            Id = 30,
                            Category = "Kitablar",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Image = "http://lorempixel.com/640/480/animals",
                            Name = "Fantastik Beton Kompyuter"
                        },
                        new
                        {
                            Id = 31,
                            Category = "садинструмент",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Image = "http://lorempixel.com/640/480/sports",
                            Name = "Fantastik Polad Sviter"
                        },
                        new
                        {
                            Id = 32,
                            Category = "Oyuncaqlar",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Image = "http://lorempixel.com/640/480/people",
                            Name = "İnanılmaz Ağac Stol"
                        },
                        new
                        {
                            Id = 33,
                            Category = "oyunlar",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Image = "http://lorempixel.com/640/480/animals",
                            Name = "İntellektual Plastik Kompyuter"
                        },
                        new
                        {
                            Id = 34,
                            Category = "Filmlər",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Image = "http://lorempixel.com/640/480/abstract",
                            Name = "Mükəmməl Ağac Stol"
                        },
                        new
                        {
                            Id = 35,
                            Category = "Səhiyyə",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Image = "http://lorempixel.com/640/480/nature",
                            Name = "Möhtəşəm Beton Kəmər"
                        },
                        new
                        {
                            Id = 36,
                            Category = "oyunlar",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Image = "http://lorempixel.com/640/480/nature",
                            Name = "İnanılmaz Beton Avtomobil"
                        },
                        new
                        {
                            Id = 37,
                            Category = "садинструмент",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Image = "http://lorempixel.com/640/480/sports",
                            Name = "Ergonomik Qranit Stul"
                        },
                        new
                        {
                            Id = 38,
                            Category = "oyunlar",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Image = "http://lorempixel.com/640/480/technics",
                            Name = "İntellektual Plastik Stul"
                        },
                        new
                        {
                            Id = 39,
                            Category = "bəzək",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Image = "http://lorempixel.com/640/480/sports",
                            Name = "Mükəmməl Beton Beret"
                        },
                        new
                        {
                            Id = 40,
                            Category = "gözəllik",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Image = "http://lorempixel.com/640/480/food",
                            Name = "Ergonomik Pambıq Kompyuter"
                        },
                        new
                        {
                            Id = 41,
                            Category = "musiqi",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Image = "http://lorempixel.com/640/480/cats",
                            Name = "Balaca Polad Avtomobil"
                        },
                        new
                        {
                            Id = 42,
                            Category = "Ayyaqqabı",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Image = "http://lorempixel.com/640/480/business",
                            Name = "Parlaq Polad Stol"
                        },
                        new
                        {
                            Id = 43,
                            Category = "bəzək",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Image = "http://lorempixel.com/640/480/fashion",
                            Name = "Möhtəşəm Beton Stol"
                        },
                        new
                        {
                            Id = 44,
                            Category = "bəzək",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Image = "http://lorempixel.com/640/480/nightlife",
                            Name = "Parlaq Plastik Sviter"
                        },
                        new
                        {
                            Id = 45,
                            Category = "Filmlər",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Image = "http://lorempixel.com/640/480/transport",
                            Name = "Ergonomik Polad Kompyuter"
                        },
                        new
                        {
                            Id = 46,
                            Category = "Kompyuterlər",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Image = "http://lorempixel.com/640/480/animals",
                            Name = "İntellektual Rezin Beret"
                        },
                        new
                        {
                            Id = 47,
                            Category = "İdman",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Image = "http://lorempixel.com/640/480/animals",
                            Name = "Möhtəşəm Polad Beret"
                        },
                        new
                        {
                            Id = 48,
                            Category = "Elektronika",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Image = "http://lorempixel.com/640/480/nightlife",
                            Name = "Əlverişli Beton Kulon"
                        },
                        new
                        {
                            Id = 49,
                            Category = "садинструмент",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Image = "http://lorempixel.com/640/480/people",
                            Name = "Əlverişli Ağac Stul"
                        },
                        new
                        {
                            Id = 50,
                            Category = "садинструмент",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Image = "http://lorempixel.com/640/480/abstract",
                            Name = "Fantastik Ağac Avtomobil"
                        },
                        new
                        {
                            Id = 51,
                            Category = "turizm",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Image = "http://lorempixel.com/640/480/transport",
                            Name = "Əlverişli Ağac Stol"
                        },
                        new
                        {
                            Id = 52,
                            Category = "Oyuncaqlar",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Image = "http://lorempixel.com/640/480/technics",
                            Name = "İntellektual Beton Beret"
                        },
                        new
                        {
                            Id = 53,
                            Category = "Ayyaqqabı",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Image = "http://lorempixel.com/640/480/animals",
                            Name = "Parlaq Qranit Beret"
                        },
                        new
                        {
                            Id = 54,
                            Category = "Oyuncaqlar",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Image = "http://lorempixel.com/640/480/food",
                            Name = "İnanılmaz Polad Beret"
                        },
                        new
                        {
                            Id = 55,
                            Category = "садинструмент",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Image = "http://lorempixel.com/640/480/abstract",
                            Name = "Ergonomik Ağac Beret"
                        },
                        new
                        {
                            Id = 56,
                            Category = "İdman",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Image = "http://lorempixel.com/640/480/nature",
                            Name = "Əlverişli Polad Stul"
                        },
                        new
                        {
                            Id = 57,
                            Category = "Ayyaqqabı",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Image = "http://lorempixel.com/640/480/cats",
                            Name = "Parlaq Qranit Stul"
                        },
                        new
                        {
                            Id = 58,
                            Category = "Elektronika",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Image = "http://lorempixel.com/640/480/food",
                            Name = "Parlaq Qranit Sviter"
                        },
                        new
                        {
                            Id = 59,
                            Category = "uşaq üçün",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Image = "http://lorempixel.com/640/480/cats",
                            Name = "İntellektual Beton Stul"
                        },
                        new
                        {
                            Id = 60,
                            Category = "Oyuncaqlar",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Image = "http://lorempixel.com/640/480/fashion",
                            Name = "Fantastik Pambıq Sviter"
                        },
                        new
                        {
                            Id = 61,
                            Category = "Ev",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Image = "http://lorempixel.com/640/480/nightlife",
                            Name = "Parlaq Pambıq Stul"
                        },
                        new
                        {
                            Id = 62,
                            Category = "uşaq üçün",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Image = "http://lorempixel.com/640/480/sports",
                            Name = "İntellektual Pambıq Sviter"
                        },
                        new
                        {
                            Id = 63,
                            Category = "gözəllik",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Image = "http://lorempixel.com/640/480/nature",
                            Name = "Balaca Ağac Kəmər"
                        },
                        new
                        {
                            Id = 64,
                            Category = "bəzək",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Image = "http://lorempixel.com/640/480/people",
                            Name = "Fantastik Beton Kəmər"
                        },
                        new
                        {
                            Id = 65,
                            Category = "Geyim",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Image = "http://lorempixel.com/640/480/abstract",
                            Name = "Ergonomik Polad Kəmər"
                        },
                        new
                        {
                            Id = 66,
                            Category = "Ev",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Image = "http://lorempixel.com/640/480/business",
                            Name = "Parlaq Beton Stul"
                        },
                        new
                        {
                            Id = 67,
                            Category = "Ev",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Image = "http://lorempixel.com/640/480/nightlife",
                            Name = "Ergonomik Plastik Sviter"
                        },
                        new
                        {
                            Id = 68,
                            Category = "bəzək",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Image = "http://lorempixel.com/640/480/city",
                            Name = "Fantastik Polad Avtomobil"
                        },
                        new
                        {
                            Id = 69,
                            Category = "Filmlər",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Image = "http://lorempixel.com/640/480/food",
                            Name = "Mükəmməl Qranit Avtomobil"
                        },
                        new
                        {
                            Id = 70,
                            Category = "gözəllik",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Image = "http://lorempixel.com/640/480/animals",
                            Name = "Kobud Polad Kəmər"
                        },
                        new
                        {
                            Id = 71,
                            Category = "Ev",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Image = "http://lorempixel.com/640/480/transport",
                            Name = "Balaca Polad Stul"
                        },
                        new
                        {
                            Id = 72,
                            Category = "Filmlər",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Image = "http://lorempixel.com/640/480/sports",
                            Name = "İnanılmaz Beton Kulon"
                        },
                        new
                        {
                            Id = 73,
                            Category = "bəzək",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Image = "http://lorempixel.com/640/480/city",
                            Name = "Əlverişli Pambıq Beret"
                        },
                        new
                        {
                            Id = 74,
                            Category = "Ev",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Image = "http://lorempixel.com/640/480/people",
                            Name = "Mükəmməl Beton Beret"
                        },
                        new
                        {
                            Id = 75,
                            Category = "Ev",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Image = "http://lorempixel.com/640/480/abstract",
                            Name = "İnanılmaz Pambıq Stul"
                        },
                        new
                        {
                            Id = 76,
                            Category = "Filmlər",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Image = "http://lorempixel.com/640/480/fashion",
                            Name = "Balaca Rezin Kompyuter"
                        },
                        new
                        {
                            Id = 77,
                            Category = "Səhiyyə",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Image = "http://lorempixel.com/640/480/fashion",
                            Name = "Fantastik Rezin Avtomobil"
                        },
                        new
                        {
                            Id = 78,
                            Category = "Geyim",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Image = "http://lorempixel.com/640/480/abstract",
                            Name = "Balaca Plastik Kəmər"
                        },
                        new
                        {
                            Id = 79,
                            Category = "Kitablar",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Image = "http://lorempixel.com/640/480/abstract",
                            Name = "İntellektual Plastik Kəmər"
                        },
                        new
                        {
                            Id = 80,
                            Category = "İdman",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Image = "http://lorempixel.com/640/480/nature",
                            Name = "Ergonomik Pambıq Sviter"
                        },
                        new
                        {
                            Id = 81,
                            Category = "Ayyaqqabı",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Image = "http://lorempixel.com/640/480/fashion",
                            Name = "İntellektual Ağac Kəmər"
                        },
                        new
                        {
                            Id = 82,
                            Category = "Kitablar",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Image = "http://lorempixel.com/640/480/sports",
                            Name = "Fantastik Beton Sviter"
                        },
                        new
                        {
                            Id = 83,
                            Category = "gözəllik",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Image = "http://lorempixel.com/640/480/city",
                            Name = "Əlverişli Polad Kəmər"
                        },
                        new
                        {
                            Id = 84,
                            Category = "musiqi",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Image = "http://lorempixel.com/640/480/fashion",
                            Name = "İntellektual Beton Stol"
                        },
                        new
                        {
                            Id = 85,
                            Category = "Ev",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Image = "http://lorempixel.com/640/480/nightlife",
                            Name = "Kobud Polad Sviter"
                        },
                        new
                        {
                            Id = 86,
                            Category = "gözəllik",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Image = "http://lorempixel.com/640/480/sports",
                            Name = "İntellektual Ağac Stol"
                        },
                        new
                        {
                            Id = 87,
                            Category = "İdman",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Image = "http://lorempixel.com/640/480/nature",
                            Name = "Balaca Qranit Beret"
                        },
                        new
                        {
                            Id = 88,
                            Category = "oyunlar",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Image = "http://lorempixel.com/640/480/sports",
                            Name = "İntellektual Beton Stol"
                        },
                        new
                        {
                            Id = 89,
                            Category = "Elektronika",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Image = "http://lorempixel.com/640/480/food",
                            Name = "Fantastik Rezin Kulon"
                        },
                        new
                        {
                            Id = 90,
                            Category = "musiqi",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Image = "http://lorempixel.com/640/480/city",
                            Name = "Mükəmməl Pambıq Avtomobil"
                        },
                        new
                        {
                            Id = 91,
                            Category = "İdman",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Image = "http://lorempixel.com/640/480/abstract",
                            Name = "İnanılmaz Qranit Stul"
                        },
                        new
                        {
                            Id = 92,
                            Category = "Avtomobil",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Image = "http://lorempixel.com/640/480/food",
                            Name = "Əlverişli Rezin Kompyuter"
                        },
                        new
                        {
                            Id = 93,
                            Category = "bəzək",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Image = "http://lorempixel.com/640/480/sports",
                            Name = "Kobud Polad Kompyuter"
                        },
                        new
                        {
                            Id = 94,
                            Category = "Ayyaqqabı",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Image = "http://lorempixel.com/640/480/cats",
                            Name = "Möhtəşəm Polad Sviter"
                        },
                        new
                        {
                            Id = 95,
                            Category = "Səhiyyə",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Image = "http://lorempixel.com/640/480/animals",
                            Name = "Balaca Qranit Sviter"
                        },
                        new
                        {
                            Id = 96,
                            Category = "Səhiyyə",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Image = "http://lorempixel.com/640/480/animals",
                            Name = "Mükəmməl Ağac Beret"
                        },
                        new
                        {
                            Id = 97,
                            Category = "uşaq üçün",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Image = "http://lorempixel.com/640/480/nature",
                            Name = "Balaca Ağac Kəmər"
                        },
                        new
                        {
                            Id = 98,
                            Category = "Ev",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Image = "http://lorempixel.com/640/480/people",
                            Name = "Balaca Qranit Stul"
                        },
                        new
                        {
                            Id = 99,
                            Category = "Geyim",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Image = "http://lorempixel.com/640/480/cats",
                            Name = "Möhtəşəm Plastik Kulon"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Serilog.Core.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Serilog.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Serilog.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Serilog.Core.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Serilog.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Serilog.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
