// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SerilogExample.DataAccess.Context;

#nullable disable

namespace SerilogExample.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240123201811_mig_1")]
    partial class mig_1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Serilog.Core.Entities.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Serilog.Core.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Serilog.Core.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Geyim",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Fantastik Polad Avtomobil"
                        },
                        new
                        {
                            Id = 2,
                            Category = "oyunlar",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Kobud Polad Avtomobil"
                        },
                        new
                        {
                            Id = 3,
                            Category = "oyunlar",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Ergonomik Qranit Sviter"
                        },
                        new
                        {
                            Id = 4,
                            Category = "gözəllik",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "İntellektual Rezin Kulon"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Kompyuterlər",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Balaca Beton Sviter"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Geyim",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Mükəmməl Rezin Kompyuter"
                        },
                        new
                        {
                            Id = 7,
                            Category = "bəzək",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "İnanılmaz Qranit Avtomobil"
                        },
                        new
                        {
                            Id = 8,
                            Category = "uşaq üçün",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Mükəmməl Qranit Sviter"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Filmlər",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Ergonomik Beton Kompyuter"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Avtomobil",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Möhtəşəm Pambıq Stul"
                        },
                        new
                        {
                            Id = 11,
                            Category = "садинструмент",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Parlaq Beton Kulon"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Kompyuterlər",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Balaca Plastik Avtomobil"
                        },
                        new
                        {
                            Id = 13,
                            Category = "İdman",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Mükəmməl Pambıq Kompyuter"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Ayyaqqabı",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Parlaq Qranit Kompyuter"
                        },
                        new
                        {
                            Id = 15,
                            Category = "садинструмент",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Ergonomik Rezin Stol"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Kitablar",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Möhtəşəm Polad Stol"
                        },
                        new
                        {
                            Id = 17,
                            Category = "oyunlar",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Balaca Rezin Beret"
                        },
                        new
                        {
                            Id = 18,
                            Category = "oyunlar",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Möhtəşəm Pambıq Kulon"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Səhiyyə",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Əlverişli Polad Kompyuter"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Geyim",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Fantastik Ağac Sviter"
                        },
                        new
                        {
                            Id = 21,
                            Category = "gözəllik",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Parlaq Plastik Stul"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Avtomobil",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Mükəmməl Pambıq Kompyuter"
                        },
                        new
                        {
                            Id = 23,
                            Category = "musiqi",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Balaca Polad Stul"
                        },
                        new
                        {
                            Id = 24,
                            Category = "oyunlar",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Kobud Plastik Stul"
                        },
                        new
                        {
                            Id = 25,
                            Category = "Elektronika",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "İnanılmaz Qranit Kulon"
                        },
                        new
                        {
                            Id = 26,
                            Category = "Elektronika",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Ergonomik Beton Kulon"
                        },
                        new
                        {
                            Id = 27,
                            Category = "Səhiyyə",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "İnanılmaz Beton Kulon"
                        },
                        new
                        {
                            Id = 28,
                            Category = "gözəllik",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "İnanılmaz Polad Stul"
                        },
                        new
                        {
                            Id = 29,
                            Category = "uşaq üçün",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "İntellektual Polad Avtomobil"
                        },
                        new
                        {
                            Id = 30,
                            Category = "bəzək",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "İntellektual Plastik Sviter"
                        },
                        new
                        {
                            Id = 31,
                            Category = "Geyim",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Balaca Beton Kulon"
                        },
                        new
                        {
                            Id = 32,
                            Category = "Filmlər",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "İnanılmaz Pambıq Stol"
                        },
                        new
                        {
                            Id = 33,
                            Category = "Avtomobil",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "İnanılmaz Polad Beret"
                        },
                        new
                        {
                            Id = 34,
                            Category = "Kitablar",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Ergonomik Qranit Stul"
                        },
                        new
                        {
                            Id = 35,
                            Category = "Oyuncaqlar",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "İntellektual Polad Kompyuter"
                        },
                        new
                        {
                            Id = 36,
                            Category = "Ayyaqqabı",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Balaca Polad Kəmər"
                        },
                        new
                        {
                            Id = 37,
                            Category = "Filmlər",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Möhtəşəm Beton Avtomobil"
                        },
                        new
                        {
                            Id = 38,
                            Category = "садинструмент",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Kobud Pambıq Kompyuter"
                        },
                        new
                        {
                            Id = 39,
                            Category = "Filmlər",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "İntellektual Rezin Avtomobil"
                        },
                        new
                        {
                            Id = 40,
                            Category = "uşaq üçün",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Ergonomik Polad Kəmər"
                        },
                        new
                        {
                            Id = 41,
                            Category = "Oyuncaqlar",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Möhtəşəm Pambıq Beret"
                        },
                        new
                        {
                            Id = 42,
                            Category = "Filmlər",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Kobud Qranit Sviter"
                        },
                        new
                        {
                            Id = 43,
                            Category = "Geyim",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "İnanılmaz Plastik Stol"
                        },
                        new
                        {
                            Id = 44,
                            Category = "Filmlər",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Ergonomik Rezin Stol"
                        },
                        new
                        {
                            Id = 45,
                            Category = "musiqi",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Fantastik Plastik Kəmər"
                        },
                        new
                        {
                            Id = 46,
                            Category = "İdman",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Mükəmməl Polad Avtomobil"
                        },
                        new
                        {
                            Id = 47,
                            Category = "turizm",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Parlaq Polad Stol"
                        },
                        new
                        {
                            Id = 48,
                            Category = "Kitablar",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Fantastik Rezin Kulon"
                        },
                        new
                        {
                            Id = 49,
                            Category = "Ev",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "İnanılmaz Qranit Kulon"
                        },
                        new
                        {
                            Id = 50,
                            Category = "musiqi",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "İnanılmaz Qranit Beret"
                        },
                        new
                        {
                            Id = 51,
                            Category = "Avtomobil",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Balaca Rezin Kulon"
                        },
                        new
                        {
                            Id = 52,
                            Category = "Kompyuterlər",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Əlverişli Qranit Kəmər"
                        },
                        new
                        {
                            Id = 53,
                            Category = "uşaq üçün",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Möhtəşəm Rezin Sviter"
                        },
                        new
                        {
                            Id = 54,
                            Category = "Avtomobil",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Parlaq Qranit Stol"
                        },
                        new
                        {
                            Id = 55,
                            Category = "Səhiyyə",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Parlaq Beton Avtomobil"
                        },
                        new
                        {
                            Id = 56,
                            Category = "İdman",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Əlverişli Polad Avtomobil"
                        },
                        new
                        {
                            Id = 57,
                            Category = "Avtomobil",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Ergonomik Rezin Kulon"
                        },
                        new
                        {
                            Id = 58,
                            Category = "uşaq üçün",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Balaca Qranit Kulon"
                        },
                        new
                        {
                            Id = 59,
                            Category = "Səhiyyə",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Ergonomik Plastik Kulon"
                        },
                        new
                        {
                            Id = 60,
                            Category = "Filmlər",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Kobud Pambıq Sviter"
                        },
                        new
                        {
                            Id = 61,
                            Category = "bəzək",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Əlverişli Plastik Kəmər"
                        },
                        new
                        {
                            Id = 62,
                            Category = "gözəllik",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Parlaq Pambıq Stol"
                        },
                        new
                        {
                            Id = 63,
                            Category = "gözəllik",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Ergonomik Plastik Stol"
                        },
                        new
                        {
                            Id = 64,
                            Category = "садинструмент",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Balaca Pambıq Avtomobil"
                        },
                        new
                        {
                            Id = 65,
                            Category = "Kitablar",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "İnanılmaz Ağac Avtomobil"
                        },
                        new
                        {
                            Id = 66,
                            Category = "садинструмент",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Parlaq Ağac Kəmər"
                        },
                        new
                        {
                            Id = 67,
                            Category = "bəzək",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Ergonomik Pambıq Kəmər"
                        },
                        new
                        {
                            Id = 68,
                            Category = "Kitablar",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "İnanılmaz Plastik Kəmər"
                        },
                        new
                        {
                            Id = 69,
                            Category = "Ev",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Möhtəşəm Rezin Stol"
                        },
                        new
                        {
                            Id = 70,
                            Category = "turizm",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Ergonomik Plastik Beret"
                        },
                        new
                        {
                            Id = 71,
                            Category = "Kompyuterlər",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Mükəmməl Polad Stul"
                        },
                        new
                        {
                            Id = 72,
                            Category = "turizm",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Ergonomik Rezin Sviter"
                        },
                        new
                        {
                            Id = 73,
                            Category = "turizm",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "İntellektual Beton Sviter"
                        },
                        new
                        {
                            Id = 74,
                            Category = "İdman",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Əlverişli Plastik Stol"
                        },
                        new
                        {
                            Id = 75,
                            Category = "bəzək",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Möhtəşəm Rezin Sviter"
                        },
                        new
                        {
                            Id = 76,
                            Category = "Səhiyyə",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Mükəmməl Plastik Kulon"
                        },
                        new
                        {
                            Id = 77,
                            Category = "gözəllik",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "İnanılmaz Ağac Stul"
                        },
                        new
                        {
                            Id = 78,
                            Category = "turizm",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Parlaq Qranit Stol"
                        },
                        new
                        {
                            Id = 79,
                            Category = "musiqi",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "İnanılmaz Plastik Avtomobil"
                        },
                        new
                        {
                            Id = 80,
                            Category = "садинструмент",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Əlverişli Rezin Stul"
                        },
                        new
                        {
                            Id = 81,
                            Category = "Elektronika",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Ergonomik Beton Stol"
                        },
                        new
                        {
                            Id = 82,
                            Category = "Səhiyyə",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Balaca Beton Kulon"
                        },
                        new
                        {
                            Id = 83,
                            Category = "Kitablar",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "İntellektual Rezin Kəmər"
                        },
                        new
                        {
                            Id = 84,
                            Category = "Elektronika",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Mükəmməl Rezin Beret"
                        },
                        new
                        {
                            Id = 85,
                            Category = "Kompyuterlər",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Mükəmməl Ağac Stol"
                        },
                        new
                        {
                            Id = 86,
                            Category = "Səhiyyə",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "İntellektual Pambıq Sviter"
                        },
                        new
                        {
                            Id = 87,
                            Category = "musiqi",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Mükəmməl Polad Kəmər"
                        },
                        new
                        {
                            Id = 88,
                            Category = "oyunlar",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Mükəmməl Ağac Avtomobil"
                        },
                        new
                        {
                            Id = 89,
                            Category = "Ayyaqqabı",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "İnanılmaz Rezin Stol"
                        },
                        new
                        {
                            Id = 90,
                            Category = "Ev",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Mükəmməl Rezin Stol"
                        },
                        new
                        {
                            Id = 91,
                            Category = "Ev",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Kobud Pambıq Avtomobil"
                        },
                        new
                        {
                            Id = 92,
                            Category = "Elektronika",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Möhtəşəm Pambıq Stul"
                        },
                        new
                        {
                            Id = 93,
                            Category = "gözəllik",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Mükəmməl Ağac Stol"
                        },
                        new
                        {
                            Id = 94,
                            Category = "Ev",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Əlverişli Ağac Sviter"
                        },
                        new
                        {
                            Id = 95,
                            Category = "İdman",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Mükəmməl Pambıq Beret"
                        },
                        new
                        {
                            Id = 96,
                            Category = "Ayyaqqabı",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Möhtəşəm Beton Avtomobil"
                        },
                        new
                        {
                            Id = 97,
                            Category = "Filmlər",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Mükəmməl Polad Kulon"
                        },
                        new
                        {
                            Id = 98,
                            Category = "Ayyaqqabı",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Kobud Plastik Sviter"
                        },
                        new
                        {
                            Id = 99,
                            Category = "садинструмент",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Ergonomik Ağac Kəmər"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Serilog.Core.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Serilog.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Serilog.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Serilog.Core.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Serilog.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Serilog.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
