// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Serilog.DataAccess.Context;

#nullable disable

namespace Serilog.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Serilog.Core.Entities.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Serilog.Core.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Serilog.Core.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Geyim",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Image = "https://picsum.photos/640/480/?image=1030",
                            Name = "Mükəmməl Beton Kompyuter"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Kitablar",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Image = "https://picsum.photos/640/480/?image=164",
                            Name = "Balaca Beton Stol"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Ayyaqqabı",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Image = "https://picsum.photos/640/480/?image=969",
                            Name = "İnanılmaz Ağac Beret"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Oyuncaqlar",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Image = "https://picsum.photos/640/480/?image=411",
                            Name = "Mükəmməl Polad Kəmər"
                        },
                        new
                        {
                            Id = 5,
                            Category = "oyunlar",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Image = "https://picsum.photos/640/480/?image=995",
                            Name = "Mükəmməl Beton Kulon"
                        },
                        new
                        {
                            Id = 6,
                            Category = "musiqi",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Image = "https://picsum.photos/640/480/?image=225",
                            Name = "İnanılmaz Beton Kompyuter"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Ayyaqqabı",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Image = "https://picsum.photos/640/480/?image=831",
                            Name = "İnanılmaz Plastik Beret"
                        },
                        new
                        {
                            Id = 8,
                            Category = "oyunlar",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Image = "https://picsum.photos/640/480/?image=515",
                            Name = "Fantastik Rezin Kəmər"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Oyuncaqlar",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Image = "https://picsum.photos/640/480/?image=541",
                            Name = "Parlaq Rezin Kompyuter"
                        },
                        new
                        {
                            Id = 10,
                            Category = "oyunlar",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Image = "https://picsum.photos/640/480/?image=1037",
                            Name = "İntellektual Beton Kulon"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Elektronika",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Image = "https://picsum.photos/640/480/?image=107",
                            Name = "İnanılmaz Polad Kompyuter"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Avtomobil",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Image = "https://picsum.photos/640/480/?image=28",
                            Name = "İnanılmaz Plastik Sviter"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Oyuncaqlar",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Image = "https://picsum.photos/640/480/?image=127",
                            Name = "İnanılmaz Plastik Kəmər"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Səhiyyə",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Image = "https://picsum.photos/640/480/?image=226",
                            Name = "İntellektual Rezin Kəmər"
                        },
                        new
                        {
                            Id = 15,
                            Category = "musiqi",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Image = "https://picsum.photos/640/480/?image=332",
                            Name = "Möhtəşəm Ağac Avtomobil"
                        },
                        new
                        {
                            Id = 16,
                            Category = "bəzək",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Image = "https://picsum.photos/640/480/?image=858",
                            Name = "Möhtəşəm Qranit Stul"
                        },
                        new
                        {
                            Id = 17,
                            Category = "İdman",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Image = "https://picsum.photos/640/480/?image=548",
                            Name = "Fantastik Ağac Stol"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Ev",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Image = "https://picsum.photos/640/480/?image=518",
                            Name = "Ergonomik Qranit Sviter"
                        },
                        new
                        {
                            Id = 19,
                            Category = "gözəllik",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Image = "https://picsum.photos/640/480/?image=21",
                            Name = "Mükəmməl Pambıq Beret"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Kitablar",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Image = "https://picsum.photos/640/480/?image=466",
                            Name = "Əlverişli Plastik Stul"
                        },
                        new
                        {
                            Id = 21,
                            Category = "musiqi",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Image = "https://picsum.photos/640/480/?image=748",
                            Name = "Balaca Rezin Stul"
                        },
                        new
                        {
                            Id = 22,
                            Category = "gözəllik",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Image = "https://picsum.photos/640/480/?image=912",
                            Name = "Kobud Beton Stol"
                        },
                        new
                        {
                            Id = 23,
                            Category = "oyunlar",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Image = "https://picsum.photos/640/480/?image=125",
                            Name = "Möhtəşəm Qranit Avtomobil"
                        },
                        new
                        {
                            Id = 24,
                            Category = "Kompyuterlər",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Image = "https://picsum.photos/640/480/?image=782",
                            Name = "Fantastik Beton Kompyuter"
                        },
                        new
                        {
                            Id = 25,
                            Category = "turizm",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Image = "https://picsum.photos/640/480/?image=650",
                            Name = "İnanılmaz Beton Kəmər"
                        },
                        new
                        {
                            Id = 26,
                            Category = "oyunlar",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Image = "https://picsum.photos/640/480/?image=557",
                            Name = "Ergonomik Pambıq Avtomobil"
                        },
                        new
                        {
                            Id = 27,
                            Category = "Geyim",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Image = "https://picsum.photos/640/480/?image=945",
                            Name = "İnanılmaz Ağac Avtomobil"
                        },
                        new
                        {
                            Id = 28,
                            Category = "oyunlar",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Image = "https://picsum.photos/640/480/?image=732",
                            Name = "İnanılmaz Polad Beret"
                        },
                        new
                        {
                            Id = 29,
                            Category = "Ayyaqqabı",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Image = "https://picsum.photos/640/480/?image=821",
                            Name = "Fantastik Ağac Stol"
                        },
                        new
                        {
                            Id = 30,
                            Category = "oyunlar",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Image = "https://picsum.photos/640/480/?image=164",
                            Name = "Möhtəşəm Ağac Beret"
                        },
                        new
                        {
                            Id = 31,
                            Category = "садинструмент",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Image = "https://picsum.photos/640/480/?image=45",
                            Name = "İntellektual Plastik Kulon"
                        },
                        new
                        {
                            Id = 32,
                            Category = "Avtomobil",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Image = "https://picsum.photos/640/480/?image=168",
                            Name = "Fantastik Polad Stol"
                        },
                        new
                        {
                            Id = 33,
                            Category = "turizm",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Image = "https://picsum.photos/640/480/?image=263",
                            Name = "İnanılmaz Rezin Stol"
                        },
                        new
                        {
                            Id = 34,
                            Category = "gözəllik",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Image = "https://picsum.photos/640/480/?image=128",
                            Name = "Ergonomik Plastik Stol"
                        },
                        new
                        {
                            Id = 35,
                            Category = "Geyim",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Image = "https://picsum.photos/640/480/?image=443",
                            Name = "Kobud Pambıq Kulon"
                        },
                        new
                        {
                            Id = 36,
                            Category = "Ev",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Image = "https://picsum.photos/640/480/?image=188",
                            Name = "Möhtəşəm Plastik Avtomobil"
                        },
                        new
                        {
                            Id = 37,
                            Category = "Avtomobil",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Image = "https://picsum.photos/640/480/?image=438",
                            Name = "İntellektual Polad Avtomobil"
                        },
                        new
                        {
                            Id = 38,
                            Category = "oyunlar",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Image = "https://picsum.photos/640/480/?image=876",
                            Name = "Parlaq Beton Kulon"
                        },
                        new
                        {
                            Id = 39,
                            Category = "Geyim",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Image = "https://picsum.photos/640/480/?image=842",
                            Name = "Əlverişli Rezin Kəmər"
                        },
                        new
                        {
                            Id = 40,
                            Category = "садинструмент",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Image = "https://picsum.photos/640/480/?image=575",
                            Name = "Ergonomik Ağac Kəmər"
                        },
                        new
                        {
                            Id = 41,
                            Category = "Elektronika",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Image = "https://picsum.photos/640/480/?image=60",
                            Name = "Ergonomik Ağac Avtomobil"
                        },
                        new
                        {
                            Id = 42,
                            Category = "Ev",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Image = "https://picsum.photos/640/480/?image=252",
                            Name = "Ergonomik Pambıq Sviter"
                        },
                        new
                        {
                            Id = 43,
                            Category = "садинструмент",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Image = "https://picsum.photos/640/480/?image=881",
                            Name = "İntellektual Ağac Stul"
                        },
                        new
                        {
                            Id = 44,
                            Category = "Avtomobil",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Image = "https://picsum.photos/640/480/?image=947",
                            Name = "İntellektual Pambıq Stul"
                        },
                        new
                        {
                            Id = 45,
                            Category = "Elektronika",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Image = "https://picsum.photos/640/480/?image=747",
                            Name = "Parlaq Qranit Sviter"
                        },
                        new
                        {
                            Id = 46,
                            Category = "turizm",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Image = "https://picsum.photos/640/480/?image=348",
                            Name = "Əlverişli Plastik Avtomobil"
                        },
                        new
                        {
                            Id = 47,
                            Category = "Səhiyyə",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Image = "https://picsum.photos/640/480/?image=14",
                            Name = "Əlverişli Polad Stol"
                        },
                        new
                        {
                            Id = 48,
                            Category = "Səhiyyə",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Image = "https://picsum.photos/640/480/?image=1036",
                            Name = "Möhtəşəm Ağac Avtomobil"
                        },
                        new
                        {
                            Id = 49,
                            Category = "musiqi",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Image = "https://picsum.photos/640/480/?image=162",
                            Name = "İnanılmaz Ağac Kəmər"
                        },
                        new
                        {
                            Id = 50,
                            Category = "Kompyuterlər",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Image = "https://picsum.photos/640/480/?image=69",
                            Name = "Balaca Ağac Kompyuter"
                        },
                        new
                        {
                            Id = 51,
                            Category = "Avtomobil",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Image = "https://picsum.photos/640/480/?image=662",
                            Name = "Möhtəşəm Ağac Avtomobil"
                        },
                        new
                        {
                            Id = 52,
                            Category = "Oyuncaqlar",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Image = "https://picsum.photos/640/480/?image=160",
                            Name = "Möhtəşəm Ağac Stol"
                        },
                        new
                        {
                            Id = 53,
                            Category = "musiqi",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Image = "https://picsum.photos/640/480/?image=868",
                            Name = "İntellektual Plastik Stul"
                        },
                        new
                        {
                            Id = 54,
                            Category = "Geyim",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Image = "https://picsum.photos/640/480/?image=715",
                            Name = "İntellektual Beton Kəmər"
                        },
                        new
                        {
                            Id = 55,
                            Category = "садинструмент",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Image = "https://picsum.photos/640/480/?image=671",
                            Name = "İnanılmaz Polad Kulon"
                        },
                        new
                        {
                            Id = 56,
                            Category = "gözəllik",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Image = "https://picsum.photos/640/480/?image=847",
                            Name = "Əlverişli Polad Kəmər"
                        },
                        new
                        {
                            Id = 57,
                            Category = "turizm",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Image = "https://picsum.photos/640/480/?image=909",
                            Name = "Mükəmməl Ağac Stul"
                        },
                        new
                        {
                            Id = 58,
                            Category = "İdman",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Image = "https://picsum.photos/640/480/?image=475",
                            Name = "İntellektual Pambıq Stul"
                        },
                        new
                        {
                            Id = 59,
                            Category = "Ayyaqqabı",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Image = "https://picsum.photos/640/480/?image=408",
                            Name = "Kobud Ağac Sviter"
                        },
                        new
                        {
                            Id = 60,
                            Category = "bəzək",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Image = "https://picsum.photos/640/480/?image=1052",
                            Name = "Ergonomik Rezin Kulon"
                        },
                        new
                        {
                            Id = 61,
                            Category = "Ayyaqqabı",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Image = "https://picsum.photos/640/480/?image=320",
                            Name = "Balaca Plastik Stul"
                        },
                        new
                        {
                            Id = 62,
                            Category = "Səhiyyə",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Image = "https://picsum.photos/640/480/?image=420",
                            Name = "Ergonomik Polad Sviter"
                        },
                        new
                        {
                            Id = 63,
                            Category = "bəzək",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Image = "https://picsum.photos/640/480/?image=18",
                            Name = "Balaca Beton Kompyuter"
                        },
                        new
                        {
                            Id = 64,
                            Category = "Kompyuterlər",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Image = "https://picsum.photos/640/480/?image=1072",
                            Name = "Parlaq Plastik Beret"
                        },
                        new
                        {
                            Id = 65,
                            Category = "Avtomobil",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Image = "https://picsum.photos/640/480/?image=552",
                            Name = "Parlaq Qranit Beret"
                        },
                        new
                        {
                            Id = 66,
                            Category = "Ayyaqqabı",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Image = "https://picsum.photos/640/480/?image=1046",
                            Name = "Balaca Plastik Kəmər"
                        },
                        new
                        {
                            Id = 67,
                            Category = "Kompyuterlər",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Image = "https://picsum.photos/640/480/?image=570",
                            Name = "Balaca Ağac Beret"
                        },
                        new
                        {
                            Id = 68,
                            Category = "Səhiyyə",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Image = "https://picsum.photos/640/480/?image=476",
                            Name = "İntellektual Pambıq Beret"
                        },
                        new
                        {
                            Id = 69,
                            Category = "musiqi",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Image = "https://picsum.photos/640/480/?image=171",
                            Name = "Fantastik Beton Kompyuter"
                        },
                        new
                        {
                            Id = 70,
                            Category = "oyunlar",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Image = "https://picsum.photos/640/480/?image=771",
                            Name = "İnanılmaz Beton Sviter"
                        },
                        new
                        {
                            Id = 71,
                            Category = "Kitablar",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Image = "https://picsum.photos/640/480/?image=576",
                            Name = "Möhtəşəm Polad Kulon"
                        },
                        new
                        {
                            Id = 72,
                            Category = "İdman",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Image = "https://picsum.photos/640/480/?image=808",
                            Name = "Mükəmməl Polad Kulon"
                        },
                        new
                        {
                            Id = 73,
                            Category = "oyunlar",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Image = "https://picsum.photos/640/480/?image=963",
                            Name = "Fantastik Plastik Stol"
                        },
                        new
                        {
                            Id = 74,
                            Category = "садинструмент",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Image = "https://picsum.photos/640/480/?image=432",
                            Name = "Mükəmməl Polad Kompyuter"
                        },
                        new
                        {
                            Id = 75,
                            Category = "bəzək",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Image = "https://picsum.photos/640/480/?image=762",
                            Name = "Parlaq Beton Avtomobil"
                        },
                        new
                        {
                            Id = 76,
                            Category = "uşaq üçün",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Image = "https://picsum.photos/640/480/?image=533",
                            Name = "Kobud Plastik Beret"
                        },
                        new
                        {
                            Id = 77,
                            Category = "Elektronika",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Image = "https://picsum.photos/640/480/?image=331",
                            Name = "Ergonomik Beton Kulon"
                        },
                        new
                        {
                            Id = 78,
                            Category = "Kompyuterlər",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Image = "https://picsum.photos/640/480/?image=17",
                            Name = "Mükəmməl Polad Stul"
                        },
                        new
                        {
                            Id = 79,
                            Category = "Elektronika",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Image = "https://picsum.photos/640/480/?image=579",
                            Name = "Möhtəşəm Beton Kəmər"
                        },
                        new
                        {
                            Id = 80,
                            Category = "Ev",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Image = "https://picsum.photos/640/480/?image=62",
                            Name = "Möhtəşəm Qranit Kəmər"
                        },
                        new
                        {
                            Id = 81,
                            Category = "садинструмент",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Image = "https://picsum.photos/640/480/?image=20",
                            Name = "Əlverişli Beton Stol"
                        },
                        new
                        {
                            Id = 82,
                            Category = "Geyim",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Image = "https://picsum.photos/640/480/?image=489",
                            Name = "Əlverişli Beton Avtomobil"
                        },
                        new
                        {
                            Id = 83,
                            Category = "садинструмент",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Image = "https://picsum.photos/640/480/?image=180",
                            Name = "İnanılmaz Ağac Kəmər"
                        },
                        new
                        {
                            Id = 84,
                            Category = "Ev",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Image = "https://picsum.photos/640/480/?image=920",
                            Name = "Ergonomik Plastik Stol"
                        },
                        new
                        {
                            Id = 85,
                            Category = "bəzək",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Image = "https://picsum.photos/640/480/?image=628",
                            Name = "İntellektual Ağac Avtomobil"
                        },
                        new
                        {
                            Id = 86,
                            Category = "oyunlar",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Image = "https://picsum.photos/640/480/?image=290",
                            Name = "Əlverişli Polad Kulon"
                        },
                        new
                        {
                            Id = 87,
                            Category = "Ev",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Image = "https://picsum.photos/640/480/?image=148",
                            Name = "Ergonomik Pambıq Stul"
                        },
                        new
                        {
                            Id = 88,
                            Category = "садинструмент",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Image = "https://picsum.photos/640/480/?image=3",
                            Name = "İnanılmaz Beton Stol"
                        },
                        new
                        {
                            Id = 89,
                            Category = "Filmlər",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Image = "https://picsum.photos/640/480/?image=97",
                            Name = "Balaca Ağac Avtomobil"
                        },
                        new
                        {
                            Id = 90,
                            Category = "musiqi",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Image = "https://picsum.photos/640/480/?image=109",
                            Name = "İntellektual Plastik Kulon"
                        },
                        new
                        {
                            Id = 91,
                            Category = "oyunlar",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Image = "https://picsum.photos/640/480/?image=876",
                            Name = "İnanılmaz Pambıq Beret"
                        },
                        new
                        {
                            Id = 92,
                            Category = "Filmlər",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Image = "https://picsum.photos/640/480/?image=167",
                            Name = "Əlverişli Pambıq Avtomobil"
                        },
                        new
                        {
                            Id = 93,
                            Category = "musiqi",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Image = "https://picsum.photos/640/480/?image=87",
                            Name = "İnanılmaz Qranit Kompyuter"
                        },
                        new
                        {
                            Id = 94,
                            Category = "Kitablar",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Image = "https://picsum.photos/640/480/?image=1009",
                            Name = "Kobud Ağac Avtomobil"
                        },
                        new
                        {
                            Id = 95,
                            Category = "uşaq üçün",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Image = "https://picsum.photos/640/480/?image=789",
                            Name = "Balaca Pambıq Avtomobil"
                        },
                        new
                        {
                            Id = 96,
                            Category = "gözəllik",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Image = "https://picsum.photos/640/480/?image=45",
                            Name = "Fantastik Polad Beret"
                        },
                        new
                        {
                            Id = 97,
                            Category = "Filmlər",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Image = "https://picsum.photos/640/480/?image=111",
                            Name = "Balaca Polad Sviter"
                        },
                        new
                        {
                            Id = 98,
                            Category = "bəzək",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Image = "https://picsum.photos/640/480/?image=1037",
                            Name = "Əlverişli Rezin Avtomobil"
                        },
                        new
                        {
                            Id = 99,
                            Category = "Elektronika",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Image = "https://picsum.photos/640/480/?image=543",
                            Name = "Kobud Rezin Avtomobil"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Serilog.Core.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Serilog.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Serilog.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Serilog.Core.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Serilog.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Serilog.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
